---
title: "Group 2 - merge data sets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(kableExtra)
library(dplyr)
library(DBI)
library(dbplyr)
library(odbc)

```


### Data cleaning - building on Joachim's example


```{r dbconnect}

#SQL connection string

con <- dbConnect(odbc::odbc(), .connection_string = "Driver={SQL Server};Server=tcp:vhb20.database.windows.net,1433;
Database=businessdata;
Uid=quant_admin;
Pwd=Deloitte1234;
Encrypt=yes;
TrustServerCertificate=no;
Connection Timeout=30", timeout = 10)

```

Reading insolvency data in August and September where subject is "Eröffnungen" directly from the database
```{r readData}

#Don't change the order here due to error -> https://github.com/r-dbi/odbc/issues/86

#SELECT * FROM dbo.insolvency FULL OUTER JOIN dbo.orbis ON dbo.insolvency.name_debtor = dbo.orbis.name_native WHERE (dbo.orbis.year >= 2017

MergedDF_all2017 <- dbGetQuery(con, "SELECT column1, date, year, closdate, insolvency_court, court_file_number, subject, name_debtor, domicile_debtor, ctryiso, bvdid, name_internat , name_native , major_sector , nace2_main_section , naceccod2 , ussicpcod , category_of_company , status_str , legalfrm , indepind , listed , conscode , filing_type , accpractice , audstatus , source , fias , cuas , stok , debt , ocas , cash , toas , shfd , ncli , culi , loan , cred , ocli , tshf , empl , opre , turn , cost , fipl , taxa , exex , pl
 FROM orbis_insolvency_merge")

#SELECT * FROM dbo.insolvency FULL OUTER JOIN dbo.orbis ON dbo.insolvency.name_debtor = dbo.orbis.name_native WHERE (dbo.insolvency.subject = 'Eröffnungen') AND (dbo.insolvency.date >= '2020-08-01') AND (dbo.insolvency.date <= '2020-09-30')

MergedDF_filtered <- dbGetQuery(con, "SELECT column1, date, year, closdate, insolvency_court, court_file_number, subject, name_debtor, domicile_debtor, ctryiso, bvdid, name_internat , name_native , major_sector , nace2_main_section , naceccod2 , ussicpcod , category_of_company , status_str , legalfrm , indepind , listed , conscode , filing_type , accpractice , audstatus , source , fias , cuas , stok , debt , ocas , cash , toas , shfd , ncli , culi , loan , cred , ocli , tshf , empl , opre , turn , cost , fipl , taxa , exex , pl FROM orbis_insolvency_merge_filtered")

```

Deleting duplicates

```{r deleteDups}
insol_de <- MergedDF_all2017 %>% unique()
```

Missing values check

```{r displayNAs}
na_vals <- insol_de %>%
  summarise_all(list( ~ sum(is.na(.))))

nas_df <- tibble(
  Variable = names(insol_de),
  `NA count` = t(na_vals)
)

kable(nas_df) %>% 
  kable_styling(full_width = FALSE)
```

```{r convert data types}

#TODO - convert selected column into numeric
MergedDF_all2017$fias <- as.numeric(MergedDF_all2017$fias)
MergedDF_all2017$cuas <- as.numeric(MergedDF_all2017$cuas)
MergedDF_all2017$stok <- as.numeric(MergedDF_all2017$stok)
MergedDF_all2017$debt <- as.numeric(MergedDF_all2017$debt)
MergedDF_all2017$ocas <- as.numeric(MergedDF_all2017$ocas)
MergedDF_all2017$cash <- as.numeric(MergedDF_all2017$cash)
MergedDF_all2017$toas <- as.numeric(MergedDF_all2017$toas)
MergedDF_all2017$shfd <- as.numeric(MergedDF_all2017$shfd)
MergedDF_all2017$ncli <- as.numeric(MergedDF_all2017$ncli)
MergedDF_all2017$culi <- as.numeric(MergedDF_all2017$culi)
MergedDF_all2017$loan <- as.numeric(MergedDF_all2017$loan)
MergedDF_all2017$cred <- as.numeric(MergedDF_all2017$cred)
MergedDF_all2017$ocli <- as.numeric(MergedDF_all2017$ocli)
MergedDF_all2017$tshf <- as.numeric(MergedDF_all2017$tshf)
MergedDF_all2017$empl <- as.numeric(MergedDF_all2017$empl)
MergedDF_all2017$opre <- as.numeric(MergedDF_all2017$opre)
MergedDF_all2017$turn <- as.numeric(MergedDF_all2017$turn)
MergedDF_all2017$cost <- as.numeric(MergedDF_all2017$cost)
MergedDF_all2017$fipl <- as.numeric(MergedDF_all2017$fipl)
MergedDF_all2017$taxa <- as.numeric(MergedDF_all2017$taxa)
MergedDF_all2017$exex <- as.numeric(MergedDF_all2017$exex)
MergedDF_all2017$pl <- as.numeric(MergedDF_all2017$pl)
lapply(MergedDF_all2017, class)

```


Generate new variables
```{r newvars}
attach(MergedDF_all2017)
MergedDF_all2017$expe <- rowSums(MergedDF_all2017[,c("cost", "fipl", "taxa", "exex")], na.rm = TRUE)
MergedDF_all2017$neti <- MergedDF_all2017$turn - MergedDF_all2017$expe
MergedDF_all2017$roa <- MergedDF_all2017$neti / MergedDF_all2017$toas
MergedDF_all2017$astu <- MergedDF_all2017$opre / MergedDF_all2017$toas
detach(MergedDF_all2017)
```

Data analysis
```{r datanalysis}
MergedDF_all2017 <- dummy_cols(MergedDF_all2017, select_columns = 'subject')
MergedDF_all2017$subject_Eröffnungen[is.na(MergedDF_all2017$subject_Eröffnungen)] <- 0
MergedDF_all2017$subject_NA[is.na(MergedDF_all2017$subject_NA)] <- 0

MergedDF_all2017 %>%
  group_by(subject, legalfrm) %>%
  summarise(N = n(), .groups = "drop")
```


Data analysis
```{r datanalysis}
MergedDF_all2017 <- dummy_cols(MergedDF_all2017, select_columns = 'subject')
MergedDF_all2017$subject_Eröffnungen[is.na(MergedDF_all2017$subject_Eröffnungen)] <- 0
MergedDF_all2017$subject_NA[is.na(MergedDF_all2017$subject_NA)] <- 0

MergedDF_all2017 %>%
  group_by(subject, major_sector) %>%
  summarise(N = n(), .groups = "drop")
```


Numerical data analysis
```{r numdataanalysis}
MergedDF_all2017 %>%
  group_by(subject) %>%
  summarise(meantoas = mean(toas, na.rm = TRUE),
            meanempl = mean(empl, na.rm = TRUE),
            meanroa = mean(roa, na.rm = TRUE),
            meanastu = mean(astu, na.rm = TRUE))
```






